# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d95fffbf57f50c4225f90133325b6a22e09b86c9b5ea9e1d095579dad485eafbc966bdcba95442db3982b72a8cfbe1edd13e35b002c6d754e22877351ad768d2

hetzner:
  secret_key_base: 7834852411c17497d3bfbe5c80b3a4b86512f99975129d181d5cb0a4ce41ad113ffb80b0739bf51baf1b2364c7ba4c82a6e7d32cff43f5a239d8321e461b594b

test:
  secret_key_base: 2bbfbe257b3d63efd5bd1c279c85b72893dee8f222dfb3b1e7a0ba5839c97df6ec11aaf43fbd156e4ae684e51e2fb38b03ce691cc0ea695ef7d28d934d5a7bba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
